### ISSUE TITLE
restApiRoot not recognized for login request

### ISSUE THREAD

**Issue by npedrini** [ISBX/isbx-loopback-cms#17]
Thanks for putting together what seems to be a very promising project.

I have my Loopback API running at `0.0.0.0:8000/v2`, however, when I try to login to the CMS it's hitting `http://0.0.0.0:8000/api/user/login?include=user`. If I `console.log` `restApiRoot` in boot-cms.js, it's properly set to `/v2`. What do I need to do differently in order to tell the CMS to POST the login to the correct url?

**Comment by coolwr** [comment]
Modify the CMS/Config.json with a property for `public.apiBaseUrl` and specify the /v2 path.

**Comment by npedrini** [comment]
Thanks. Unfortunately that has no effect though. 

It looks like index.js line 286 is passing `options.basePath` to the client. However, even when setting that, Config.js defaults to `/api/` in all cases, whereas it seems like it should be looking to `window.config.apiBaseUrl` first and defaulting to `/api/` if it's not set. If I switch that line around to the following, login posts to the expected url:
`apiBaseUrl: window.config.apiBaseUrl || '/api/',`

**Comment by npedrini** [comment]
Addressed in f3700246a5aba65791e89c2bdea25552bd1cd3ed
