### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by terehov** [ISBX/isbx-loopback-cms#5]
Hi! 

I have a hard time trying to set it up, since the wiki entry is hidden (not public) I don't know how to set up the /CMS/config.json.

Would be nice if you could provide a sample file. 

cheers, 

e.

**Comment by coolwr** [comment]
Hi Eugene,

I apologize for the difficulty to setup. We are still in the early stages
of development on this project and so documentation is very scarce. We've
fixed the wiki link that was going to a private wiki. Here is the direct
link to the setup and sample config.json

https://github.com/ISBX/isbx-loopback-cms/wiki/Installing-the-ISBX-CMS

--kelly

**Comment by terehov** [comment]
Great, thanks!
Now it seems to work :-) Looks promising! 
I was actually starting to build a CMS based on loopback as well, so maybe we can join forces!

**Comment by terehov** [comment]
Sorry, me again. It seems to run and the mongo DB looks good. Collections ACL, Role, RoleMapping and User are there incl. data. 
I can see the entry with admin@example.com inside User, however it seems to be impossible to log in. 

Same goes for the in memory DB. 

Any ideas? 

cheers

**Comment by coolwr** [comment]
Hi Eugene,

We've got live projects running in-memory db, sqlite, postgres, and mysql.
Surprisingly we haven't used the CMS with mongo db yet, however, it should
work.

Can you describe how you are logging in? Are their records in the Role and
RoleMapping tables?

--kelly

**Comment by coolwr** [comment]
Yes, that would be great if you want to help contribute to the loopback CMS
we are working on. We've spent quite a bit of development on what we have
so far. It requires a lot more documentation and also some refactoring. We
have used the CMS on several of our clients ranging across various
industries and for different purposes like basic website/mobile app content
management, administrative dashboards, statistics and analysis reporting,
and eve surveying and data collection.

The CMS user interface is heavily based on Angular JS and Bootstrap using
many of the angular-ui modules. We also have support for google chart
integration for nice charts and graphs.

--kelly

**Comment by terehov** [comment]
Yes, there are. I can see the login screen but cannot log in using the test credentials mentioned in doc. 

here is my user Obj. 
{
    "_id" : ObjectId("55c762b53a61d82d52076d9d"),
    "username" : "admin",
    "password" : "$2a$10$tu4Z7Vc/LcLB9siGfxB1yew/cpEr3f8Ers67z8UQTovA6F/Shuetq",
    "email" : "admin@example.com",
    "created" : ISODate("2015-08-09T14:24:53.372Z")
}

**Comment by coolwr** [comment]
Hi Eugene,

Can you send me your config.json? It maybe the defaultnav item is not set
properly and thus is always redirecting you back to the login screen.

One thing to check is use web inspector on the login screen is to see if
the call to the POST call is made to the /api/Users/login remote method and
if it returns back an HTTP status of 200 or not.

-k

**Comment by terehov** [comment]
Yep, login seems to work -> 200
/Roles -> 404


<img width="875" alt="screen shot 2015-08-17 at 14 26 35" src="https://cloud.githubusercontent.com/assets/490885/9304809/67f5b7e6-44ec-11e5-85f7-537e6b90e1f0.png">
<img width="1109" alt="screen shot 2015-08-17 at 14 30 20" src="https://cloud.githubusercontent.com/assets/490885/9304817/85decacc-44ec-11e5-84af-1210b6c4c24c.png">

And here is my config.json:

  "public": {
    "address": "0.0.0.0",
    "port": 3005,
    "title": "ISBX CMS",
    "css": "/css/custom.css",
    "authModel": "Users",
    "profileModel": "User",
    "profileKey": "id",
    "defaultNav": {
      "route": "list",
      "params": {
        "model": "users"
      }
    },

**Comment by coolwr** [comment]
Hi Eugene,

In your `/server/model-config.json` you'll need to make `Role` and `RoleMapping` public so that the CMS can retrieve the user's role information.

For in-memory DB you can do add the following:

```
"RoleMapping": {
    "dataSource": "db",
    "public": true
},
"Role": {
    "dataSource": "db",
    "public": true
}
```

**Comment by coolwr** [comment]
I also updated the documentation to add the above step:

https://github.com/ISBX/isbx-loopback-cms/wiki/Installing-the-ISBX-CMS

**Comment by terehov** [comment]
Yeah, I am in and I can manage users. 
But how can I create pages and menu structures? 

Do you guys have any more documentation?

**Comment by coolwr** [comment]
You can setup your navigation in the `config.json` by adding to the `nav` property array as demonstrated in the installation instructions: https://github.com/ISBX/isbx-loopback-cms/wiki/Installing-the-ISBX-CMS

The config.json navigation allows you to quickly setup navigation to generate lists for each model on your database and when clicking into the list item get an edit screen to edit the model record. See how we did it for the User model.

However, if you want more flexibility like creating your own custom views you can also add custom modules like your own angularJS page controllers as documented here (I just updated the documentation with some more details on adding custom URL routing in config.json):

https://github.com/ISBX/isbx-loopback-cms/wiki/Custom-Modules
