### ISSUE TITLE
angular error on missing property object

### ISSUE THREAD

**Issue by Martodox** [ISBX/isbx-loopback-cms#9]
Hi. I wand to start off by staying that I rely appreciate your work!

I'v found a but we might discuss about.

Let's say you have a model that extends default User, call it Account

I am unable to add or edit record unless I map every property from User to Account by hand, it doesn't read extended models. The same goes for RoleMapping, `TypeError: Cannot read property 'id' of undefined` because field id isn't explicitly stated in RoleMapping model, but uses `"idInjection": true` param.

To draw a bigger picture, we are working on an open source [project](https://github.com/Contactis/translations-manager) and I am trying to implement your CMS into it for convenience. 

Let me know if you require anything else from me and how can we fix this issue :)

**Comment by coolwr** [comment]
Hi Martodox, 

Glad to hear you are using the CMS! It's still in early stages, but we are already using it in several production environments and it is pretty stable. There is a lot yet to be documented and we are in the process of getting some of that documentation into our wiki.

I forked your open source project and figured out the problem. Looks like there was a misconfiguration in the CMS/config.json. I was able to correct it and issued a pull request back into your repo.

I also added some tweaks to your account.json model showing you how to customize the display the of the model in the CMS edit view. 

I also tried adding in the role reference field into the account.json, but ran into a problem with getting the role to display. I'll have to look into it further later today, but wanted to get you setup properly. 

Please reach out with any further questions/comments. Thanks!
